Repository pires/go-proxyproto, pull requests merged in 2021-01, with the labels that each got.

#61 Support v1 UNKNOWN and v2 UNSPEC when command is LOCAL
  addr_proto.go
  header.go
  protocol.go
  v1.go
  v1_test.go
  v2.go
  v2_test.go
Labels: enhancement

#62 v2: read length and skip the bytes for UNSPEC
  v2.go
  v2_test.go
Labels: bug

#64 v1: fix command always LOCAL
  header.go
  header_test.go
  v1.go
  v1_test.go
  v2.go
  version_cmd.go
Labels: bug

#66 license: set year and copyright owner
  LICENSE
Labels: documentation
